name: Android Debug Build CI

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-android:
    name: Build Android Debug APK
    runs-on: ubuntu-latest # Menggunakan runner Linux terbaru

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install Node Dependencies
        run: npm install

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Uncomment (hapus # di awal baris) jika Opsi 1 gagal atau Anda butuh kontrol lebih
      # - name: Setup Android SDK
      #   uses: android-actions/setup-android@v3 # Action komunitas untuk setup Android SDK
      #   # Tidak perlu `with` jika versi SDK/NDK default cukup
      #   # Jika perlu versi spesifik, tambahkan:
      #   # with:
      #   #   api-level: 33 # Ganti dengan API level target Anda
      #   #   build-tools: 33.0.2 # Ganti dengan versi build tools Anda
      #   #   ndk-version: 25.2.9519653 # Ganti jika perlu NDK versi spesifik

      - name: Setup Gradle Cache # Cache dependensi Gradle untuk mempercepat build
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        run: chmod +x ./android/gradlew
        working-directory: ./

      - name: Build Android Debug APK
        run: ./gradlew assembleDebug --no-daemon
        working-directory: ./android

      - name: Upload Debug APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error
